services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  IntelligentIntern\Neo4jBundle\Service\:
    resource: '../src/Service/*'
    public: true
    tags:
      - { name: 'graphdb.strategy' }

