services:
  IntelligentIntern\Neo4jBundle\Service\:
    resource: '../src/Service/*'
    public: true
    tags:
      - { name: 'graphdb.strategy' }

  App\Factory\GraphDBServiceFactory:
    arguments:
      $vaultService: '@App\Service\VaultService'
      $logServiceFactory: '@App\Factory\LogServiceFactory'
      $graphDBResolver: '@App\Domain\GraphDBResolver'